var searchData=
[
  ['sample_20types_6516',['Sample Types',['../group__audio__aica__samples.html',1,'']]],
  ['sampling_20modes_6517',['Sampling Modes',['../group__pvr__filter__modes.html',1,'']]],
  ['scene_20submission_6518',['Scene Submission',['../group__pvr__scene__mgmt.html',1,'']]],
  ['scif_6519',['SCIF',['../group__system__scif.html',1,'']]],
  ['sd_20card_6520',['SD Card',['../group__vfs__sd.html',1,'']]],
  ['section_20header_20flags_6521',['Section Header Flags',['../group__elf__hdrflags.html',1,'']]],
  ['section_20header_20types_6522',['Section Header Types',['../group__elf__sections.html',1,'']]],
  ['settings_6523',['Settings',['../group__vmu__settings.html',1,'']]],
  ['shading_20modes_6524',['Shading Modes',['../group__pvr__shading__types.html',1,'']]],
  ['sleeping_6525',['Sleeping',['../group__tmu__sleep.html',1,'']]],
  ['sockets_6526',['Sockets',['../group__networking__sockets.html',1,'(Global Namespace)'],['../group__vfs__sockets.html',1,'(Global Namespace)']]],
  ['sound_20effects_6527',['Sound Effects',['../group__audio__sfx.html',1,'']]],
  ['sources_6528',['Sources',['../group__netcfg__srcs.html',1,'']]],
  ['special_20section_20indices_6529',['Special Section Indices',['../group__elf__specsec.html',1,'']]],
  ['speed_20values_6530',['Speed Values',['../group__modem__speeds.html',1,'']]],
  ['stack_20traces_6531',['Stack Traces',['../group__debugging__stacktrace.html',1,'']]],
  ['status_20values_6532',['Status Values',['../group__cd__status__values.html',1,'']]],
  ['store_20queues_6533',['Store Queues',['../group__store__queues.html',1,'']]],
  ['streaming_6534',['Streaming',['../group__audio__streaming.html',1,'']]],
  ['structure_6535',['Structure',['../group__bfont__indicies.html',1,'']]],
  ['subcode_20audio_20status_6536',['Subcode Audio Status',['../group__cd__subcode__audio.html',1,'']]],
  ['symbol_20binding_20types_6537',['Symbol Binding Types',['../group__elf__binding.html',1,'']]],
  ['symbol_20types_6538',['Symbol Types',['../group__elf__symtype.html',1,'']]],
  ['syscall_20command_20codes_6539',['Syscall Command Codes',['../group__cd__cmd__codes.html',1,'']]],
  ['system_6540',['System',['../group__system.html',1,'']]],
  ['system_20calls_6541',['System Calls',['../group__system__calls.html',1,'']]]
];
