name: Build Docker Images

on: [push]

jobs:
  build-gcc-kos-container:
    name: Build GCC for KOS Container
    runs-on: ubuntu-latest

    steps:
      # - run: |
      #       sudo apt install qemu-user-static \
      #       && docker run --rm --privileged multiarch/qemu-user-static --reset -p yes \
      #       && sudo systemctl restart docker \
      #       && docker buildx inspect --bootstrap

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        # with:
        #   driver-opts: network=host

      # - run: docker buildx inspect

      - name: Build and Export Container
        uses: docker/build-push-action@v2
        with:
          # load: true
          context: .
          file: ./.github/workflows/gcc-build-kos/Dockerfile
          # build-args: |
          #   PARENT_CONTAINER=localhost:5000/kos/gcc-build-deps:lastest
          # tags: localhost:5000/kos/gcc-build-kos:latest
          tags: kos/gcc-build-kos:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload Container Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gcc-build-kos
          path: /tmp/image.tar
