name: Build Docker Images

on: [push]

jobs:
  build-gcc-deps-container:
    name: Create GCC Build Deps Container
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000

    steps:
      # - run: |
      #       sudo apt install qemu-user-static \
      #       && docker run --rm --privileged multiarch/qemu-user-static --reset -p yes \
      #       && sudo systemctl restart docker \
      #       && docker buildx inspect --bootstrap

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - run: docker buildx inspect

      - name: Build and Export Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/gcc-build-deps/Dockerfile
          push: true
          tags: localhost:5000/kos/gcc-build-deps:latest
          # tags: kos/gcc-build-deps:latest
          # outputs: type=docker,dest=/tmp/image.tar

      # - name: Upload Container Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: gcc-build-deps
      #     path: /tmp/image.tar

  build-gcc-kos-container:
    name: Build GCC for KOS Container
    runs-on: ubuntu-latest
    needs: build-gcc-deps-container

    steps:
      # - run: |
      #       sudo apt install qemu-user-static \
      #       && docker run --rm --privileged multiarch/qemu-user-static --reset -p yes \
      #       && sudo systemctl restart docker \
      #       && docker buildx inspect --bootstrap

      - name: Checkout Source
        uses: actions/checkout@v3

      # - name: Download Container Artifacts
      #   uses: actions/download-artifact@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with: 
          driver: docker-container

      # - name: Download Images
        # run: docker pull localhost:5000/kos/gcc-build-deps:latest

      # - name: Load Docker images from previous workflows
      #   run: docker load --input gcc-build-deps/image.tar 
      # - run: docker image ls
      - run: docker buildx inspect

      - name: Build and Export Container
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          file: ./.github/workflows/gcc-build-kos/Dockerfile
          build-args: |
            PARENT_CONTAINER=localhost:5000/kos/gcc-build-deps:lastest
          tags: localhost:5000/kos/gcc-build-kos:latest
          # tags: kos/gcc-build-kos:latest
          # outputs: type=docker,dest=/tmp/image.tar

      # - name: Upload Container Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: gcc-build-kos
      #     path: /tmp/image.tar
