name: Build Docker Images

on: [push]

jobs:
  build-gcc-kos-container:
    name: Build GCC for KOS Container
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      PUSH_REGISTRY=localhost:5000

    steps:
      # - run: |
      #       sudo apt install qemu-user-static \
      #       && docker run --rm --privileged multiarch/qemu-user-static --reset -p yes \
      #       && sudo systemctl restart docker \
      #       && docker buildx inspect --bootstrap

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          # increase max log size
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760

      # - name: Login to Github Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build GCC Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/containers/gcc-build-kos/Dockerfile
          # build-args: |
          #     BUILD_CORES=${{ steps.cpu-cores.outputs.count }}
          tags: $PUSH_REGISTRY/${{ GITHUB_ACTOR }}/sh4-gcc-patched-kos:latest
          # outputs: type=oci,dest=/tmp/toolchain.tar
          push: true


      - name: Build KOS Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/containers/kos/Dockerfile
          build-args: |
            SRC_REGISTRY=$PUSH_REGISTRY
          tags: $PUSH_REGISTRY/${{ GITHUB_ACTOR }}/kos:latest
          push: true
          # outputs: type=oci, 

      # - name: Upload Container Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: gcc-build-kos
      #     path: /tmp/toolchain.tar
