name: Build Docker Images

on: [push]

jobs:
  build-gcc-deps-container:
    name: Create GCC Build Deps Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/gcc-build-deps/Dockerfile
          tags: kos-gcc-build-deps:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload Container Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gcc-build-deps
          path: /tmp/image.tar

  build-gcc-kos-container:
    name: Build GCC for KOS Container
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2

      - name: Load Docker images from previous workflows
        run: docker load --input gcc-build-deps/image.tar 

      - run: docker image ls
