name: Build Docker Images

on: [push]

jobs:
  build-gcc-deps-container:
    name: Create GCC Build Deps Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-gcc-build-deps
          tags: ${{ github.repository }}-gcc-build-deps:latest
          outputs: type=oci,dest=/tmp/image.tar

      - name: Upload Container Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gcc-build-deps
          path: /tmp/image.tar
