name: Build KOS Documentation
on: workflow_dispatch

jobs:
  build-docs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Build Docs
        run: |
          sudo apt-get install -y doxygen
          make docs

      - name: Upload Dreamcast Examples
        uses: actions/upload-artifact@v4
        with:
          name: dreamcast-kos-docs
          path: ${{ github.workspace }}/kos/doc/reference
